//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H3_AirPort
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirportTerminal
    {
        public int AirportId { get; set; }
        public string IATA { get; set; }
        public string AirportName { get; set; }
        public string TerminalName { get; set; }
        public Nullable<int> RouteId { get; set; }
        public Nullable<int> ZipCode { get; set; }
    
        public virtual FlightRoute FlightRoute { get; set; }
        public virtual City City { get; set; }
    }
}
