//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H3_AirPort
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightRoute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlightRoute()
        {
            this.AirportTerminal = new HashSet<AirportTerminal>();
            this.Operater = new HashSet<Operater>();
        }
    
        public int RouteId { get; set; }
        public string Departure { get; set; }
        public string Arrival { get; set; }
        public Nullable<int> RouteOwner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AirportTerminal> AirportTerminal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operater> Operater { get; set; }
    }
}
